// data.js: everything the portfolio site displays, and nothing else.
//
// Resume and CV wording does not live here. Those documents are built by the job-application
// workflow (job-search/, outside this repo) and published as static PDFs in docs/. Wording here
// follows the same facts ledger; run job-search/tools/check.py on site/js before every push.
// A card's "slug" is its link anchor (#slug); keep it stable because sent resumes link to it.
// "aliases" are old anchors that still open the card.

export const SITE = {
  person: {
    name: "Elijah Andrae",
    headline: "Data Scientist for Semiconductor Manufacturing | Design of experiments, metrology, cleanroom fabrication, and statistical modeling",
    photo: "images/headshot.jpg",
    photoAlt: "Eli Andrae headshot",
    domains: ["Cleanroom Fabrication", "Design of Experiments", "Metrology", "Python & R", "Simulation & ML"],
    contact: {
      email: "elijah.andrae56@outlook.com",
      linkedin: "https://www.linkedin.com/in/elijah-andrae",
      github: "https://github.com/elijah-andrae56",
      portfolio: "https://elijah-andrae56.github.io/Portfolio/",
    },
    summary: "I'm a data science graduate (University of Oregon, 2026; Mathematics and Business minors) who earned the degree doing semiconductor process work in a cleanroom. I wrote 26 cleanroom SOPs, each checked off by lab staff, ran a term of designed experiments in JMP across oxidation, spin coating, evaporation, and lithography, and spent a year designing, fabricating, and testing microfluidic electrochemical devices. The habit I bring from that work is checking the measurement before trusting the result: in one deposition experiment the tool, not the recipe, turned out to be the largest source of variation. On the data side, I build simulations and machine learning models from large, imperfect records and test them on data they never saw. I'm from Erie, Pennsylvania, a US citizen, and ready to relocate.",
  },
  pipeline: [
    {
      id: "engineering",
      stage: "01",
      role: "Build",
      title: "Engineering",
      deck: "Physical systems, fabricated, measured, and characterized in the lab.",
      groups: [
        {
          name: "Nanofabrication",
          items: [
            "ISO 6 and ISO 4 cleanroom operations (26 SOPs)",
            "Photolithography (spin coat, bakes, alignment, dose)",
            "Thin-film processing (thermal evaporation, e-beam, lift-off, etching)",
            "Thermal oxidation",
            "Multilayer alignment",
            "Substrate prep, UV-ozone cleaning",
          ],
        },
        {
          name: "Optics & Metrology",
          items: [
            "Free-space optical alignment",
            "Interferometry (Michelson, Fabry-Perot)",
            "Polarization & beam profiling",
            "Dektak, ellipsometry, reflectometry",
            "Optical microscopy",
          ],
        },
        {
          name: "Electronics & Instrumentation",
          items: [
            "Keithley 2450 SMU",
            "Oscilloscopes & photodetectors",
            "Semiconductor probe station",
            "Analog signal conditioning",
            "Microcontroller prototyping (Arduino)",
            "DAQ & instrument control",
          ],
        },
        {
          name: "Design & CAD",
          items: ["KLayout, CLEWin (mask design)", "AutoCAD, Fusion 360", "Process flow documentation"],
        },
      ],
    },
    {
      id: "data",
      stage: "02",
      role: "Model",
      title: "Data Science",
      deck: "Code, statistics, and machine learning that turn experiments into models.",
      groups: [
        {
          name: "Programming & Tooling",
          items: [
            "Python (pandas, NumPy, scikit-learn, PyTorch, Matplotlib)",
            "R (tidyverse)",
            "SQL, Bash, LaTeX",
            "Git / GitHub",
            "Jupyter, RMarkdown",
          ],
        },
        {
          name: "Statistics & Inference",
          items: [
            "Regression (OLS, logistic, Poisson, ridge / lasso)",
            "ANOVA, t-tests, chi-square",
            "Bootstrap, A/B testing, KS tests",
            "Censored maximum likelihood",
            "Time-series summarization",
          ],
        },
        {
          name: "Machine Learning",
          items: [
            "Classification (KNN, random forests, gradient boosting)",
            "PCA & clustering",
            "Neural networks (MLP, CNN) in PyTorch",
            "Hyperparameter tuning, cross-validation",
            "Feature engineering",
            "Model evaluation",
          ],
        },
        {
          name: "Mathematical Foundations",
          items: [
            "Stochastic processes (Math 467)",
            "Mathematical statistics (Math 461)",
            "Linear algebra (Math 341, 342)",
            "Cryptography (Math 458)",
            "Markov chains, discrete-event simulation",
          ],
        },
      ],
    },
    {
      id: "analytics",
      stage: "03",
      role: "Decide",
      title: "Analytics & Strategy",
      deck: "Experimental design, decision analytics, and communication that close the loop.",
      groups: [
        {
          name: "Experimental Design",
          items: [
            "DOE (full & fractional factorials)",
            "Process optimization",
            "Interaction modeling",
            "Metrology cross-checks",
            "Multivariate analysis",
            "Train / test on held-out data",
          ],
        },
        {
          name: "Decision Analytics",
          items: ["Marketing & operational analytics", "Sentiment analysis", "Predictive modeling for decisions", "A/B testing"],
        },
        {
          name: "Analytical Tooling",
          items: ["JMP, SPSS", "Excel, Tableau", "Google Cloud (analytics + ETL)", "Meta Business Suite"],
        },
        {
          name: "Communication & Leadership",
          items: [
            "Technical writing",
            "Stakeholder presentations",
            "Cross-functional collaboration",
            "Instructional support & mentorship",
            "Project scoping",
            "Results translation",
          ],
        },
      ],
    },
  ],
  cards: [
    {
      kind: "research",
      featured: true,
      title: "Electrochemical Microbubble Devices: Fabrication, Characterization, and Stochastic Signal Applications",
      org: "Independent Research, Alemán Lab, University of Oregon",
      date: "2026-03-11",
      categories: ["nanofab", "ds", "cs"],
      tags: ["Nanofab", "Microfluidics", "Device Physics", "Instrumentation", "Research"],
      tools: [
        "CleWin",
        "KLayout",
        "Photomask design",
        "Photolithography",
        "LaserWriter",
        "Thin-film deposition",
        "E-beam deposition",
        "PDMS soft lithography",
        "Keithley 2450",
        "Semiconductor probe station",
        "Optical microscopy",
        "Python",
      ],
      blurb: "Year-long independent research on electrochemical microbubble generation in microfluidic devices: photomask design, full fabrication, semiconductor-style electrical characterization, automated measurement, and stochastic modeling. Directions include microfluidic actuation, stochastic device concepts, and entropy-source studies.",
      details: "Two device generations, designed, fabricated, and characterized end to end. I drew the photomask sets in CleWin and KLayout, built the devices in the cleanroom, and tested them on a Keithley 2450 and a semiconductor probe station with automated Python acquisition: 80+ test runs across about 20 devices on four chips. The second generation addresses seven measurement channels through a shared-electrode matrix from a reduced pad count.\n\nThe modules below cover the fabrication stack, the characterization and modeling workflow, and where the platform could go.",
      image: "images/microfluidic_electrolysis_1.jpg",
      images: [
        "images/microfluidic_electrolysis_1.jpg",
        "images/microfluidic_electrolysis_3.jpg",
        "images/microfluidic_electrolysis_4.jpg",
        "images/microfluidic_electrolysis_5.jpg",
        "images/microfluidic_electrolysis_6.jpg",
      ],
      imageAlt: "Electrochemical microbubble microfluidic device and characterization workflow",
      modules: [
        {
          title: "Device Design and Fabrication",
          tools: ["CleWin", "Photolithography", "Thin-film deposition", "Lift-off", "SU-8 molds", "PDMS soft lithography"],
          blurb: "Photomasks drawn for two device generations, then a full fabrication flow from bare glass to working prototypes.",
          bullets: [
            "Drew the photomask sets for both device generations in CleWin, defining electrode geometry, gap spacing, interlayer alignment marks, and bond-pad routing on a 25 mm mask frame.",
            "Ran the full fabrication flow: substrate cleaning, photolithography, thin-film metal deposition and lift-off, dielectric insulation, SU-8 mold fabrication, and PDMS channel integration on glass, producing six working prototypes.",
            "Designed electrode geometry, gap spacing, alignment, insulation openings, and channel layout so bubble generation could be studied as a controlled physical effect rather than a one-off demonstration.",
          ],
        },
        {
          title: "Characterization, Instrumentation, and Modeling",
          tools: ["Keithley 2450", "Semiconductor probe station", "Python (SCPI)", "Censored MLE"],
          blurb: "Semiconductor-style electrical characterization, automated acquisition, and stochastic modeling of the first event.",
          bullets: [
            "Characterized activation thresholds, current response, field and gap dependence, and trial-to-trial variability on a Keithley 2450 and semiconductor probe station.",
            "Automated synchronized acquisition in Python (SCPI instrument control, logging, structured datasets) for repeatable test campaigns: 80+ runs across about 20 devices on four chips.",
            "Modeled the first-event time as a stochastic process with an activation model derived from reaction kinetics, using censored maximum likelihood so trials with no event stayed in the data.",
          ],
        },
        {
          title: "Application Directions",
          tools: ["Microfluidic actuation", "Stochastic device concepts", "Entropy characterization"],
          blurb: "One platform, several directions: microfluidic actuation, stochastic device concepts, and entropy-source studies.",
          bullets: [
            "The same platform supports several directions, which is why the characterization was done carefully rather than to a single spec.",
            "Directions include microfluidic actuation, stochastic device concepts, and entropy-source studies where randomness is measured rather than assumed.",
          ],
        },
      ],
      links: [],
    },
    {
      kind: "lab",
      title: "Nanofabrication Cleanroom Labs (PHYS 495) - DOE-Driven Process Development",
      priority: 10,
      org: "PHYS 495 Nanofabrication, University of Oregon",
      date: "2025-12-01",
      categories: ["nanofab", "ds"],
      tags: ["Nanofab", "Cleanroom", "DOE", "Factorial Design", "Metrology", "JMP"],
      tools: [
        "JMP (DOE / screening designs)",
        "Lindberg tube furnace",
        "Laurell spin coater",
        "Angstrom Covap thermal evaporator",
        "Süss MJB4 mask aligner",
        "Microtech LaserWriter",
        "Filmetrics F20/F40 reflectometry",
        "Woollam ellipsometry",
        "Bruker Dektak profilometry",
        "UV-ozone / O2 plasma",
        "Wet etch and lift-off",
      ],
      blurb: "A term of cleanroom process development run as a designed-experiment program: four factorial designs (two 2⁴, two 2³) plus a 12-level exposure dose test, about 60 designed runs, with reduced-model analysis and metrology cross-checks in JMP.",
      details: "PHYS 495 Nanofabrication treats the cleanroom as a statistics problem: each process module is set up as a designed experiment in JMP, run on real tools, measured with 10-point metrology maps, and reduced to a model whose factors, interactions, and residuals have to survive diagnostics before any process recommendation is made.\n\nOver the term I designed, ran, or analyzed four factorial designs (two 2⁴ and two 2³), a 12-level exposure dose test, and a three-lens dose profile: about 60 designed runs and several hundred point-level thickness measurements. Experiments were analyzed on group data and again on pooled class data with tool and instrument as blocks. In the evaporation experiment that second look mattered: the evaporator block was the strongest factor in the pooled model, so the tool, not the recipe, was the largest source of variation. I suspected crystal-monitor drift on one tool, reported it to lab staff, and recommended logging the in-situ monitor on every run.\n\nThe modules below follow the term in order, from cleanroom qualification and DOE fundamentals through oxidation, deposition, lithography, pattern transfer, and multilayer registration.",
      image: "images/alignment.jpg",
      images: [
        "images/cleanroom_gowned.jpg",
        "images/alignment.jpg",
        "images/dose_test_1.png",
        "images/dose_test_2.jpg",
        "images/lift_off.png",
        "images/wet_etch.png",
      ],
      imageAlt: "Eli gowned in the ISO 6 cleanroom, and results from the PHYS 495 labs",
      modules: [
        {
          title: "Lab A - Cleanroom Qualification and SOP Development",
          date: "2025-10-02",
          tools: ["ISO 6 cleanroom", "Fume hood", "Sonicator", "March O2 etcher", "Solvent bench"],
          bullets: [
            "Wrote 26 standard operating procedures, each checked off by lab staff, qualifying for independent use of the tools and processes they cover in an ISO 6 (Class 1000) cleanroom; also trained to enter an ISO 4 (Class 10) cleanroom.",
            "Topics included cleanroom entry, solvent handling, the fume hood, DI water, die scribing and cleaning, the ultrasonic cleaner, hotplate, UV-ozone, tube furnace, thermal evaporator, photoresist, spin coater, mask aligner, LaserWriter, developer, lift-off, and metal etching.",
            "Each SOP documented hazards, the ways the instrument could be broken, and before, during, and after steps: the documentation habit used in every later lab.",
          ],
          blurb: "Cleanroom qualification: 26 SOPs, each checked off by lab staff, from cleanroom entry through deposition, lithography, and pattern transfer.",
        },
        {
          title: "Lab α - Design of Experiments Foundations (JMP)",
          date: "2025-10-14",
          tools: ["JMP", "ANOVA", "Tukey HSD / Fisher LSD", "Residual diagnostics"],
          bullets: [
            "Worked through a full one-way comparative-experiment sequence in JMP: hypothesis testing, ANOVA, Tukey HSD and Fisher LSD post-hoc comparisons, and confidence intervals, on textbook semiconductor process datasets (Montgomery) including C2F6 plasma-etch uniformity and photoresist bake temperature.",
            "Built the diagnostic habits used for the rest of the term - normal quantile plots, Shapiro-Wilk and Anderson-Darling normality tests, residual-vs-predicted checks for heteroscedasticity, and Levene/Brown-Forsythe/Bartlett equality-of-variance testing - including recognizing when a heavy-tailed response invalidates a standard ANOVA and re-analyzing under unequal variance.",
            "Practiced experiment framing end to end: response selection, design vs constant vs nuisance factor classification, and the distinction between replication and repeated measurement.",
          ],
          blurb: "DOE and statistical-inference foundations in JMP: ANOVA, post-hoc comparison, residual diagnostics, and variance testing on process data.",
        },
        {
          title: "Lab B - Thermal Oxidation and Spin Coating: Two 2⁴ Factorials",
          date: "2025-10-26",
          tools: ["Lindberg tube furnace", "Laurell spin coater", "AZ1512", "Filmetrics F20/F40", "JMP"],
          bullets: [
            "Thermal oxidation (2⁴, 16 runs, an instructor-designed class experiment blocked by lab section): my group ran two of the runs and I analyzed the class data, with oxidant (O2/H2O), temperature (900/1100 °C), time (40/160 min), and N2 carrier flow (0/2 SCFH) as factors and thickness measured at 10 points per chip on two reflectometers.",
            "Reduced the oxidation model to oxidant and temperature as dominant effects, retained an oxidant×N2 interaction on the strength of a Tukey HSD check, and reported optimal settings with intervals: maximum predicted 703 nm (95% CI [489, 917]) at H2O, 1100 °C, 160 min, 0 SCFH.",
            "Spin coating (2⁴): designed a randomized full factorial in JMP with a lab partner on acceleration, final spin speed, time at speed, and initial resist coverage, with three responses: mean resist thickness, thickness standard deviation, and die coverage estimated from chip photographs.",
            "Found final spin speed dominant for thickness and acceleration dominant for coverage (every run exceeded the 1000 nm target, so the target sat outside the design space); with the Filmetrics instrument as a block on pooled class data, the block did not survive reduction, evidence that F20 and F40 readings were interchangeable (difference in means 0.1, p = 0.9991).",
          ],
          blurb: "Two 2⁴ full factorials in one lab: silicon thermal oxidation and photoresist spin coating, each modeled on group and pooled class data with instrument blocking.",
        },
        {
          title: "Lab C - Physical Vapor Deposition: 2³ Factorial Thermal Evaporation",
          date: "2025-11-02",
          tools: ["Angstrom Covap evaporators (East, West)", "Bruker Dektak", "JMP"],
          bullets: [
            "Ran a randomized 2³ screening experiment for 100 nm Al thermal evaporation, varying chip location on the stage (center/edge), stage rotation (0/100%), and deposition rate (0.5/3 Å/s), with mean thickness and thickness standard deviation as paired responses.",
            "Masked chips with Kapton, logged chamber pump-down time to 3×10⁻⁶ hPa as a covariate, and measured 10 profilometry points per chip; a Y²-transformed thickness model reached R² = 0.97 with deposition rate significant plus rotation×rate and location×rate interactions.",
            "Re-analyzed on pooled class data with evaporator (East/West Covap) as a block: the block was the strongest factor in the model. Isolating center-stage chips showed the two tools differed in both mean thickness and standard deviation.",
            "Compared pump-down times between tools (East 25.5 s, s.d. 5.8, N = 24; West 18.1 s, s.d. 3.2, N = 8). I suspected crystal-monitor drift on the East tool but could not confirm it because most groups had not logged monitor readings, so I reported it to lab staff and recommended logging the in-situ monitor on every run.",
          ],
          blurb: "2³ factorial on thermal evaporation in which the deposition tool, not the recipe, turned out to be the largest source of variation.",
        },
        {
          title: "Lab D - Photolithography Dose Response and Instrument Cross-Validation",
          date: "2025-11-09",
          tools: ["Süss MJB4", "Microtech LaserWriter", "Woollam ellipsometer", "Filmetrics F40", "Dektak"],
          bullets: [
            "Ran a randomized 12-level dose test (35 to 200 mJ/cm² in 15 mJ steps) on a Süss MJB4: coated and soft-baked a 50 mm wafer, diced it into 16 chips, measured lamp power before each exposure to convert dose to exposure time, then exposed, post-exposure baked, developed, and hard baked in run order.",
            "Built the exposure-response curve from profilometry depth data after a matched-pairs check showed the reflectometer channel was too noisy, finding D0 about 109 mJ/cm² and D100 about 120 mJ/cm², and recommended 115 mJ/cm² as the process dose.",
            "Characterized dose profiles for three LaserWriter objective lenses over 50 to 250 mJ/cm², recording strip count, strip width, spot size, depth of focus, and filter transmission per lens; ANOVA across lenses returned p < 0.0001, with lenses 3 and 4 statistically similar and lens 5 distinct.",
            "Cross-validated three thickness metrology tools on the Lab B oxide samples: matched-pairs testing showed F20 and F40 statistically equivalent while the ellipsometer differed, and multivariate correlation put every pair near r = 1 with ellipsometer-F40 highest at 0.9999; stylus depth and reflectometer Δt agreed (p = 0.454, mean difference 0.14 µm).",
          ],
          blurb: "Exposure dose response on two exposure tools plus a three-instrument thickness metrology cross-check.",
          images: ["images/dose_test_1.png", "images/dose_test_2.jpg"],
          imageAlt: "Photolithography dose test chips and exposure response curves",
        },
        {
          title: "Lab E - Resolution 2³ Factorial, Lift-Off, and Wet Etch",
          date: "2025-11-23",
          tools: ["Microtech LaserWriter", "Covap evaporator", "Transene Type-A etchant", "Dektak", "JMP"],
          bullets: [
            "Ran a randomized 2³ factorial on LaserWriter resolution, with D-step (1/12), dose (75/200 mJ/cm²), and lens (3/5) as factors and the mean width and depth of 1, 2, 4, and 8 µm stitch-test lines as eight responses.",
            "Fit and reduced eight separate response models (R² from 0.31 to 0.999), reported which models failed to reach significance, and ran a combined desirability optimization across all eight to land on D-step 12, 200 mJ/cm², and lens 5 as the best overall resolution setting.",
            "Executed a full lift-off sequence - UV-ozone dehydration, spin coat, MJB4 CPW exposure at 100 mJ/cm², develop, 100 nm Al evaporation at 3 Å/s with 50% rotation, acetone strip with sonication - yielding 96.26 nm mean Al thickness at 2.27 nm standard deviation.",
            "Built the complementary subtractive route on Al-coated glass with Transene Type-A etchant and a diluted AZ-340 comparison etch, measuring 96.83 ± 1.38 nm and 97.83 ± 1.80 nm across two chips, estimating etch rate from breakthrough time; the wet-etch edges were visibly cleaner than lift-off.",
          ],
          blurb: "A 2³ factorial on direct-write resolution with eight responses, plus additive (lift-off) and subtractive (wet etch) pattern transfer compared on the same metrics.",
          images: ["images/lift_off.png", "images/wet_etch.png"],
          imageAlt: "Aluminum lift-off and wet etch pattern transfer results",
        },
        {
          title: "Lab F - Layer Registration and Multilayer Alignment",
          date: "2025-12-05",
          tools: ["Süss MJB4", "Microtech LaserWriter", "PMGI/AZ bilayer", "Remover PG", "Dektak"],
          bullets: [
            "Prepared PMGI SF2 / AZ1512 bilayer resist with a two-step spin program and TMAH-based AZ 300 MIF development to produce the undercut profile required for clean metal lift-off.",
            "Registered a two-layer MOSFET pattern on the Süss MJB4 by iterating x-y and rotational alignment between paired hard-mask fiducials, depositing 5 nm Cr / 50 nm Au on layer one and 50 nm Al on layer two with Remover PG lift-off between layers.",
            "Repeated the build as a three-layer direct-write process on the LaserWriter using saved A/B alignment marks and a focal plane defined from multiple reference points, then compared the mask-aligner and direct-write routes.",
            "Checked overlay with optical microscopy and Dektak alignment-marker maps on both routes (a qualitative check; no numeric overlay error was measured).",
          ],
          blurb: "Multilayer Cr/Au and Al registration through a PMGI/AZ bilayer, aligned two ways - mask aligner fiducials and LaserWriter A/B marks - and verified by Dektak marker mapping.",
          images: ["images/alignment.jpg"],
          imageAlt: "Layer alignment markers and profilometry scan",
        },
      ],
      links: [],
    },
    {
      kind: "lab",
      title: "Electronics Laboratory",
      org: "Independent Laboratory Sequence, University of Oregon",
      date: "2026-03-11",
      categories: ["cs", "ds", "nanofab", "electronics"],
      tags: ["Circuit Analysis", "Instrumentation", "Analog Electronics", "Optoelectronics"],
      tools: [
        "Oscilloscope",
        "Function Generator",
        "Power Supplies",
        "Fluke 179 Multimeter",
        "Capacitance / Inductance Meters",
        "Optical Power Meter",
        "Spectrometer",
        "Proto-boards",
      ],
      blurb: "Twelve-area independent electronics sequence: passive components, RC and LC behavior, impedance and resonance, diodes and transistors, op-amps and instrument loading, RF design, and optoelectronic devices.",
      details: "Completed the University of Oregon Electronics Obstacle Course, a 12-area independent laboratory sequence (Winter 2026, instructor Bryan Boggs). The emphasis is measurement discipline: build the circuit, predict what it should do, measure it, and explain the gap.\n\nHighlights from my write-up: five 100 Ω resistors all inside their ±5% tolerance; RC rise and fall times of 11.1 ms that scaled with capacitance; voltage shifting from a resistor to an inductor between 50 Hz and 1 MHz as inductive reactance grew; an LC resonance peak near 1.6 kHz compared against simulation; a voltage divider that sagged under multimeter loading, measured again through a unity-gain op-amp buffer; RF tank circuits built and measured on a proto-board; and photodiode, LED, and laser diode curves showing photocurrent rising with light and laser output climbing sharply above threshold. Diode behavior was modeled first in LTspice (forward and reverse knees, a diode clamp, junction capacitance) and then measured on a Keithley source-measure unit.",
      image: "images/electronics_1.jpg",
      images: [
        "images/electronics_1.jpg",
        "images/electronics_2.jpg",
        "images/electronics_3.jpg",
        "images/electronics_4.jpg",
        "images/electronics_5.jpg",
      ],
      modules: [
        {
          title: "Passive Components and RC Dynamics",
          tools: ["Fluke 179 DMM", "Capacitance meter", "Function generator", "Oscilloscope"],
          blurb: "Resistor, capacitor, and inductor fundamentals through dividers, filters, and time-domain response.",
          bullets: [
            "Measured five 100 Ω resistors, all within their ±5% tolerance, and confirmed the predicted 25 mA at 2.5 V.",
            "Measured RC rise and fall times of 11.1 ms and showed they scale with capacitance; designed RC high- and low-pass filters with a 3 dB point near 1.06 kHz.",
          ],
        },
        {
          title: "Impedance, Reactance, and Resonance",
          tools: ["LC networks", "Function generator", "Oscilloscope", "Circuit simulation"],
          blurb: "Frequency-dependent impedance and LC resonance, measured against simulated response.",
          bullets: [
            "Measured the voltage across a resistor and an inductor from 50 Hz to 1 MHz, showing voltage move to the inductor as its reactance grows with frequency.",
            "Measured an LC circuit from 100 Hz to 6.2 kHz, found a resonance peak near 1.6 kHz, and compared it with simulation.",
          ],
        },
        {
          title: "Semiconductor Devices",
          tools: ["Keithley 2450", "LTspice", "Bipolar transistor (TIP31C)", "Power supplies"],
          blurb: "Diode I-V curves modeled in LTspice and measured on a Keithley; transistor current gain measured on the bench.",
          bullets: [
            "Modeled diode forward and reverse knees (about 0.7 V and 6 to 7 V), a diode clamp, and bias-dependent junction capacitance in LTspice, then measured diode I-V curves on a Keithley source-measure unit.",
            "Measured base and collector currents on a bipolar transistor to confirm current amplification.",
          ],
        },
        {
          title: "Operational Amplifiers, Loading, and Buffering",
          tools: ["Op-amps", "Proto-boards", "Oscilloscope", "High-impedance dividers"],
          blurb: "Op-amp gain configurations plus the instrument-loading problem a buffer solves.",
          bullets: [
            "Built inverting and non-inverting amplifiers and compared gain with the feedback-resistor ratio.",
            "Measured how a multimeter's input impedance makes a high-impedance divider sag, then measured the same divider through a unity-gain buffer.",
          ],
        },
        {
          title: "RF Behavior and Board Construction",
          tools: ["LC tank circuits", "Proto-board", "Oscilloscope"],
          blurb: "RF tank circuits on a proto-board, and why components stop behaving ideally at radio frequencies.",
          bullets: [
            "Built and measured RF tank circuits on a proto-board.",
            "Worked through how parasitic capacitance, lead inductance, self-resonance, and rising losses change component behavior at RF, and why compact layouts, RF-rated parts, and ground-plane boards help.",
            "Designed LC low- and high-pass filters (100 µH with 1 nF; 1 µH with 28 pF).",
          ],
        },
        {
          title: "Optoelectronic Device Measurement",
          tools: ["Photodiodes", "LEDs", "Laser diode + constant-current driver", "Optical power meter"],
          blurb: "Photodiode, LED, and laser diode curves with optical power measurement.",
          bullets: [
            "Measured photodiode I-V curves in forward and reverse bias, in the dark, in ambient light, and under laser light; more light shifted the curve by adding photocurrent.",
            "Measured LED optical power against forward voltage and a laser diode's power-current curve, driven from a constant-current protection circuit, with output rising sharply above threshold.",
          ],
        },
      ],
      links: [
        {
          label: "Obstacle Course",
          url: "https://newjune.uoregon.edu/mediawiki/index.php/Electronics_Obstacle_Course",
        },
      ],
    },
    {
      kind: "project",
      title: "Emergency Dispatch Capacity Simulation",
      slug: "emergency-dispatch-capacity-simulation",
      aliases: ["cahoots-applied-data-science-lab"],
      org: "Independent research, extending DSCI 410L coursework",
      date: "2026-09-01",
      categories: ["ds", "cs"],
      tags: ["Data Science", "Simulation", "Public Data", "Work in Progress"],
      tools: [
        "Python",
        "pandas",
        "Discrete-event simulation",
        "Markov chains",
        "Censored MLE",
        "PyTorch",
        "Gradient-boosted trees",
        "LaTeX",
      ],
      blurb: "Work in progress. A simulation built from about 1.2 million public dispatch records estimates what more crisis-van capacity would have bought Eugene's CAHOOTS program: one more van from 11 a.m. to 10 p.m. cuts the routine median wait by about half.",
      details: "CAHOOTS sent crisis workers instead of police to mental-health and welfare calls in Eugene, Oregon. This project started as my DSCI 410L class analysis in 2024 and grew into independent research. The public dispatch record cannot answer capacity questions directly: a call closing is not a van coming free, requests that never got a van are invisible before May 2022, and the record names only a call's lead unit.\n\nSo I rebuilt what the record never logged (van shifts and van-free times, reconstructed from the sequence of dispatches) and built a discrete-event simulation from measured pieces: arrivals, job times, shifts, and diversion to police. Six behavior settings were fitted on May 2022 to 2023 and tested on 2024, a year the model never saw, with a typical miss of about 16 to 21% per measure.\n\nIn the model, one more van from 11 a.m. to 10 p.m. cuts the routine median wait by about half and requests closed without a van by about a third, across every calibration that fits. As a check, a neural network trained on the dispatch decision learned the same rule the simulator uses.\n\nA full write-up and the code are on the way.",
      image: "images/dispatch_capacity_by_hour.png",
      images: ["images/dispatch_capacity_by_hour.png", "images/dispatch_capacity_scenarios.png"],
      imageAlt: "Simulated median routine wait by hour, as staffed and with one added van",
      links: [],
    },
    {
      kind: "project",
      title: "FishTracker App",
      date: "2025-09-15",
      categories: ["cs"],
      tags: ["CS", "App Dev"],
      tools: ["Python", "Kivy", "SQL", "ETL"],
      blurb: "Offline-first mobile app in Python and Kivy that logs GPS routes and links each catch to live NOAA wave, wind, and water conditions in a SQLite data model.",
      details: "Engineered a robust mobile application to track fishing performance and environmental conditions. The app features an offline-first architecture using SQLite and Peewee ORM, ensuring data persistence even in remote locations without cellular service.\n\nKey Technical Implementations:\n\n- GPS Tracking Engine: singleton geolocation service using plyer to interface with Android hardware, including simulation mode for deterministic desktop testing.\n- Asynchronous Data Ingestion: threaded polling of WQDataLive API endpoints to fetch real-time wave height, wind speed, and water temperature without blocking the UI.\n- Data Correlation: links each logged catch with GPS coordinates and current weather conditions.\n- Configurable Architecture: unit conversion system enabling toggling between Imperial and Metric standards.",
      image: "images/fishtracker.png",
      imageAlt: "FishTracker screenshot",
      links: [
        {
          label: "Code",
          url: "https://github.com/Elijah-Andrae56/FishingTracker",
        },
      ],
    },
    {
      kind: "project",
      title: "Google Merchandise Store Analysis",
      date: "2025-03-18",
      categories: ["ds", "marketing"],
      tags: ["Data Science", "Marketing"],
      tools: ["R", "BigQuery", "tidyverse", "Logistic regression", "SQL"],
      blurb: "Analyzed 900,000+ e-commerce sessions with SQL on BigQuery and R; logistic regression models predicted purchase likelihood to inform campaign timing.",
      details: "End-to-end analysis of 903,000+ Google Merchandise Store sessions spanning Aug 2016 to Aug 2017. Data extracted from Google Cloud using SQL, cleaned and feature-engineered in R, and merged with a global holiday dataset to quantify temporal purchasing behavior.\n\nExploratory analysis examined revenue concentration by traffic source, browser, country, and visitor behavior.\n\nLogistic regression models predicted purchase likelihood and bounce behavior to support campaign timing optimization.",
      image: "images/google_merch_store_1.png",
      images: ["images/google_merch_store_1.png", "images/google_merch_store_2.png"],
      imageAlt: "Google merchandise store analysis visualization",
      links: [
        {
          label: "Code",
          url: "https://github.com/Elijah-Andrae56/Google_Merch_Store_Analysis_MKTG415",
        },
      ],
    },
    {
      kind: "project",
      title: "Lake Erie Weather-Buoy Safety Model",
      date: "2024-11-10",
      categories: ["ds", "cs"],
      tags: ["Data Science", "Python"],
      tools: ["Python", "scikit-learn", "PCA", "Ridge regression"],
      blurb: "Merged 61,000+ Lake Erie buoy observations with Erie airport weather and predicted wave height with ridge regression and PCA (holdout RMSE about 0.29 ft).",
      details: "Goal: understand and predict wave conditions off Presque Isle for small-boat safety.\n\nData: 61,448 buoy observations at a 20-minute cadence (2014 to 2021) merged with Erie airport daily weather. Cleaned missing values, standardized timestamps, and built seasonal subsets and wind-direction features.\n\nInference: wave conditions differed sharply by wind direction (ANOVA F = 362).\n\nPrediction: cross-validated forward feature selection with interaction terms, then ridge regression and PCA plus ridge, reaching a holdout RMSE of about 0.29 ft. Wind speed and gust interactions were the strongest predictors.",
      image: "images/wave_project_1.png",
      images: ["images/wave_project_1.png", "images/wave_project_2.png", "images/wave_project_3.png"],
      imageAlt: "Wave safety model results plot",
      links: [
        {
          label: "Code",
          url: "https://github.com/Elijah-Andrae56/Lake-Erie-Weather-Buoy-Project",
        },
      ],
    },
    {
      kind: "project",
      title: "Resident-Assistant Shift Scheduler",
      date: "2024-10-29",
      categories: ["cs", "ds"],
      tags: ["CS", "Optimization"],
      tools: ["Python", "OR-Tools", "Constraint optimization"],
      blurb: "Developed a model to automate RA on-call scheduling under 8+ fairness constraints; designed for 12 teams with projected 750+ hours saved yearly.",
      details: "Designed and implemented a constraint optimization model to automate the scheduling of Resident Assistant (RA) on-call shifts across 12 teams. The model incorporates a comprehensive set of constraints reflecting university policies, fairness considerations, and coverage requirements, including:\n\n- Maximum shift limits per RA\n- Fair distribution of weekend and holiday shifts\n- Coverage requirements for each time slot\n- Avoidance of back-to-back shifts\n- Accommodations for known unavailability\n\nUsing Python and Google's OR-Tools, the model generates feasible schedules that satisfy all constraints while optimizing for equitable shift distribution. Initial testing indicates that the automated scheduler can produce compliant schedules in seconds, with an estimated annual time savings of 750+ administrative hours compared to manual scheduling processes.",
      image: "images/scheduler_1.png",
      images: ["images/scheduler_1.png", "images/scheduler_2.png", "images/scheduler_3.png"],
      imageAlt: "Scheduler results",
      links: [],
    },
    {
      kind: "project",
      title: "Superconductor Critical Temperature Modeling",
      date: "2026-03-12",
      categories: ["ds", "cs"],
      tags: ["Data Science", "Machine Learning", "Materials Data"],
      tools: ["Python", "pandas", "scikit-learn", "PCA", "Random Forest", "Matplotlib"],
      blurb: "Random forest predicting superconducting critical temperature for 21,000+ compounds (test R² 0.93), with PCA and clustering to map the materials feature space.",
      details: "This project analyzes a large superconducting materials dataset containing over 21,000 compounds with features derived from elemental properties such as thermal conductivity, atomic mass, density, and valence electron structure.\n\nThe analysis combines unsupervised and supervised learning methods to explore structure in the materials feature space and evaluate whether compositional descriptors can predict superconducting critical temperature (Tc).\n\nDimensionality reduction using Principal Component Analysis (PCA) revealed clear structure in the feature space, while K-Means clustering separated materials into distinct compositional groups. When high-temperature superconductors were highlighted, they concentrated strongly within one region of this space, suggesting that certain combinations of elemental properties are associated with elevated Tc.\n\nA Random Forest regression model was then trained to predict Tc from the compositional descriptors. On held-out compounds it reached R² 0.930 (RMSE 8.97 K), with 5-fold cross-validated R² of 0.926.\n\nFeature importance identified thermal-conductivity descriptors (the range and the weighted geometric mean across constituent elements) as the dominant predictors, about two thirds of total importance; electronic-structure descriptors were secondary.",
      image: "images/superconductor_ml_1.png",
      images: ["images/superconductor_ml_1.png", "images/superconductor_ml_2.png", "images/superconductor_ml_3.png"],
      imageAlt: "Machine learning analysis of superconducting materials and critical temperature prediction",
      links: [
        {
          label: "Code",
          url: "https://github.com/Elijah-Andrae56/Superconductor_ML_Analysis.git",
        },
      ],
    },
    {
      kind: "lab",
      title: "Optical Systems & Interferometry Laboratory",
      org: "Independent Laboratory Sequence, 16 stations, University of Oregon",
      date: "2026-06-01",
      categories: ["nanofab", "process", "physics"],
      tags: ["Optics", "Laser Alignment", "Interferometry", "Hardware Characterization"],
      tools: ["HeNe Lasers", "Oscilloscopes", "Thorlabs Optomechanics", "Photodetectors", "Waveplates", "Interferometers"],
      blurb: "Completed the 16-station UO Optics Obstacle Course: built and characterized free-space optical systems, including Michelson interferometry and a scanning confocal Fabry-Perot cavity, with Thorlabs optomechanics and HeNe lasers.",
      details: "Completed the University of Oregon Optics Obstacle Course (Spring 2026), a 16-station laboratory sequence in which each station (alignment, measurement, or system build) is demonstrated and signed off before moving on. The course runs from laser safety and optics handling through beam alignment and polarization control, into quantitative beam characterization, and finally into multi-element builds: telescopes, optical isolators, a Michelson interferometer, and a Fabry-Perot cavity.\n\nThe emphasis throughout is on doing alignment properly rather than approximately, and on cross-checking a measurement by a second method wherever possible: optical power by meter against a photodetector and oscilloscope, refractive index by Brewster's angle against interferometry.\n\nThe stations below group the course into its major skill areas.",
      image: "images/optics_4.jpg",
      images: ["images/optics_1.jpg", "images/optics_2.jpg", "images/optics_3.jpg", "images/optics_4.jpg"],
      imageAlt: "Various optical experiments",
      modules: [
        {
          title: "Beam Alignment and Laser Safety",
          tools: ["HeNe laser", "Mirrors", "Irises", "Thorlabs optomechanics"],
          bullets: [
            "Established a level, vertically polarized beam at a controlled 4-inch height using mirror pairs and two irises referenced to the optical table hole pattern.",
            "Executed laser safety and beam-containment protocols and performed proper handling and cleaning of precision optics.",
          ],
          blurb: "The alignment and safety foundation every later station depends on.",
        },
        {
          title: "Polarization Control and Optical Isolation",
          tools: ["Polarizers", "Polarizing beamsplitter cubes", "Quarter waveplates", "Rotation stages"],
          bullets: [
            "Measured transmitted power through a rotating polarizer against Malus's law, characterized vertical, horizontal, and 45-degree states through polarizing beamsplitter cubes, and generated circular polarization with quarter waveplates.",
            "Built two optical isolators (polarizer plus quarter waveplate, and polarizing beamsplitter plus quarter waveplate) and explained why a Faraday rotator isolator works better.",
            "Measured Brewster's angle on a glass cover slip near 56 degrees, giving a refractive index of about 1.54.",
          ],
          blurb: "Polarization state control, isolator construction, and Brewster's-angle index measurement.",
        },
        {
          title: "Power Measurement and Detector Response",
          tools: ["Optical power meter", "DET10A / DET110 photodiodes", "Optical chopper", "Oscilloscope", "ND filters"],
          bullets: [
            "Measured laser power with a calibrated power meter (about 1.5 mW) and with a photodetector and oscilloscope using detector responsivity (about 1.7 mW), agreeing within 13%, and worked with neutral-density filters.",
            "Compared rise times of small-area (DET10A) and large-area (DET110) silicon photodiodes with a chopper: the smaller detector was faster because of its lower junction capacitance.",
          ],
          blurb: "Two independent power-measurement methods cross-checked, plus photodiode rise-time characterization.",
        },
        {
          title: "Gaussian Beam Characterization and Telescopes",
          tools: ["500 µm pinhole", "Translation stage", "Photodiode", "Newport KPX lenses"],
          bullets: [
            "Built a 1:2 beam expander from two lenses and checked collimation.",
            "Measured the 1/e² beam width by scanning a 500 µm pinhole across the beam on a translation stage (13.5% points near 1.30 mm and 1.95 mm).",
            "Worked through spherical aberration, coma, astigmatism, and chromatic aberration, and how lens orientation and an iris reduce spherical aberration.",
          ],
          blurb: "Beam expander construction, pinhole-scan beam profiling, and aberration behavior.",
        },
        {
          title: "Interferometry and Fabry-Perot Cavity",
          tools: ["Michelson interferometer", "Non-polarizing beamsplitter", "Confocal spherical-mirror cavity"],
          bullets: [
            "Built a Michelson interferometer and measured refractive index by fringe counting: 34 fringes for a glass slide against 29 predicted, and an index of about 2.4 for an unknown sample.",
            "Measured the laser's coherence length at about 15 cm.",
            "Built a scanning confocal Fabry-Perot cavity from 10 cm focal-length mirrors (L = 20 cm, free spectral range 375 MHz), calculated a theoretical resolution of 12.6 MHz, and worked through what limits the finesse of a real cavity.",
          ],
          blurb: "Michelson interferometry for refractive index and coherence length, plus a scanning confocal Fabry-Perot cavity.",
        },
      ],
      links: [
        {
          label: "Obstacle Course",
          url: "https://newjune.uoregon.edu/mediawiki/index.php/Optics_Obstacle_Course",
        },
      ],
    },
    {
      kind: "project",
      title: "Course Reference Sheets (LaTeX)",
      slug: "course-reference-sheets",
      aliases: ["mathematical-rigor-analytical-evaluation"],
      org: "University of Oregon coursework",
      date: "2026-06-01",
      categories: ["ds", "cs"],
      tags: ["LaTeX", "Mathematics", "Statistics", "Machine Learning"],
      tools: ["LaTeX (XeLaTeX)", "Probability", "Stochastic processes", "Machine learning", "Multivariable calculus"],
      blurb: "Two-page LaTeX reference sheets that condense a full course each: machine learning, stochastic processes, multivariable calculus, probability, statistics, data structures, and finance.",
      details: "I wrote these for my exams and kept refining them until each course fit on two dense pages: definitions, formulas, decision rules for choosing a method, and the traps I kept falling into. The machine learning sheet ends in model and metric routing tables; the stochastic processes sheet covers Markov chain classification, stationary distributions, hitting times, mixing rate, and Brownian motion.\n\nThe public versions are concept sheets only: worked homework, quiz, and practice-exam solutions were removed. Source and compiled PDFs are on GitHub.",
      image: "images/notesheets_dsci372.png",
      images: ["images/notesheets_dsci372.png", "images/notesheets_math467.png", "images/notesheets_math281.png"],
      imageAlt: "Page one of a LaTeX course reference sheet",
      links: [
        {
          label: "GitHub",
          url: "https://github.com/Elijah-Andrae56/course-notesheets",
        },
      ],
    },
  ],
  experience: [
    {
      title: "Resident Assistant",
      track: "industry",
      meta: "University of Oregon Housing - Eugene, OR | Sept 2023 to June 2026",
      bullets: [
        "Mentored and supported 180+ students in dormitory housing; provided conflict mediation, academic guidance, and day-to-day support.",
        "Delivered on-call first-response assistance during medical, wellness, and facilities incidents; coordinated with professional staff and emergency services.",
        "Conducted safety inspections, policy education, and incident documentation to ensure adherence to university standards.",
        "Led community programming focused on engagement, well-being, and resource accessibility.",
      ],
    },
    {
      title: "Learning Assistant - Applied Data Science for Social Justice",
      track: "academic",
      domains: ["ds", "cs", "nanofab"],
      meta: "University of Oregon - Eugene, OR | Apr 2025 to June 2026",
      bullets: [
        "Facilitated lab sessions and office hours; guided students through cleaning, visualization, and analysis of CAHOOTS dispatch logs.",
        "Coached analytical storytelling and partner-facing presentations for community stakeholders (White Bird Clinic).",
        "Provided individualized technical support in Python/pandas workflows for reproducible, impact-oriented insights.",
      ],
    },
    {
      title: "Social Media Analytics and Marketing Intern",
      track: "industry",
      domains: ["ds", "marketing"],
      meta: "Humes - Waterford, PA | Jun 2023 to Aug 2023",
      bullets: [
        "Increased organic reach by 117% within three weeks by analyzing engagement metrics and optimizing cadence in Meta Business Suite.",
        "Conducted competitive content analysis and audience segmentation to refine messaging strategy and improve engagement consistency.",
      ],
    },
    {
      title: "Mathematics Paper Marker",
      track: "academic",
      domains: ["ds", "cs", "nanofab"],
      meta: "University of Oregon - Eugene, OR | Mar 2025 to June 2026",
      bullets: [
        "Evaluated assignments and provided detailed feedback to support proof-writing, matrix methods, cryptographic reasoning, and statistical modeling.",
        "Collaborated with instructors to maintain grading accuracy, rubric adherence, and timely feedback delivery.",
      ],
    },
  ],
  coursework: [
    {
      title: "Data Science and Computing",
      meta: "",
      bullets: [
        "Machine Learning for Data Science",
        "Probability and Statistics for Data Science",
        "Principles and Techniques of Data Science",
        "Data Structures in Python",
        "Data Science for Social Justice",
        "Foundations of Data Science I and II",
        "Computer Science I and II",
      ],
    },
    {
      title: "Mathematics and Statistics",
      meta: "",
      bullets: [
        "Stochastic Processes",
        "Mathematical Methods of Statistics",
        "Elementary Linear Algebra I and II",
        "Several-Variable Calculus I and II",
        "Calculus I to III",
        "Introduction to Differential Equations",
        "Introduction to Mathematical Cryptography",
        "Introduction to Proof",
      ],
    },
    {
      title: "Nanofabrication and Engineering",
      meta: "",
      bullets: [
        "Nanofabrication (PHYS 495)",
        "Research: Quantum & Nanotech (PHYS 401), microfluidic device research",
        "Electronics Obstacle Course",
        "Optics Obstacle Course",
      ],
    },
    {
      title: "Business and Marketing Analytics",
      meta: "",
      bullets: [
        "Marketing Analytics",
        "Marketing Research",
        "Finance: Creating Value through Capital",
        "Accounting: Language of Business Decisions",
        "Spreadsheet Analysis (Excel)",
        "Micro and Macro Economics",
      ],
    },
    {
      title: "Ethics and Analytical Reasoning",
      meta: "",
      bullets: ["Data Ethics", "Critical Reasoning"],
    },
  ],
  education: [
    {
      title: "University of Oregon",
      meta: "B.S. Data Science (Marketing Analytics concentration) - Minors: Mathematics, Business Administration | 2022 to 2026",
      bullets: [
        "Dean's List: Spring 2025, Fall 2025",
        "Relevant coursework: Nanofabrication, Machine Learning, Probability and Statistics, Stochastic Processes, Linear Algebra, Differential Equations",
      ],
    },
    {
      title: "Cathedral Preparatory School",
      meta: "High school - Erie, PA | 2018 to 2022",
      bullets: [],
    },
  ],
};

export const CATEGORY_LABELS = {
  all: "All",
  research: "Research",
  lab: "Labs",
  project: "Projects",
  ds: "Data Science",
  cs: "Computer Science",
  marketing: "Marketing",
  nanofab: "Nanofabrication",
};
